### ISSUE TITLE
How to lint the code?

### ISSUE THREAD

**Issue by gaearon** [voronianski/flux-comparison#59]
The contributing guide suggests using ESLint, and there's a `.eslintrc` in the project root, but `eslint` is not in `devDependencies`. After adding it there and running it, I got (literally) over 9000 violations:

<img width="815" alt="screen shot 2015-09-29 at 20 43 20" src="https://cloud.githubusercontent.com/assets/810438/10172985/c42eefe4-66ea-11e5-9b94-4757436a980a.png">

Should we remove the section on using ESLint from Contributing, as well as `.eslintrc`? It seems to do more harm than good at this point. :-)

**Comment by voronianski** [comment]
@gaearon I'm using eslint validator in Sublime Text 3 and it currently shows no errors at all..

**Comment by gaearon** [comment]
Hmm. You're using global eslint then, right? Maybe 1.x doesn't work but 0.x works?

**Comment by voronianski** [comment]
@gaearon I've updated eslint globally and see some indent errors now, but I'm a bit stuck with it:

<img src="https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-09-29%20%D0%B2%2021.03.07.png" width="600" />

``` bash
/Users/dmitri/github/flux-comparison/redux/js/reducers/products.js
  11:9   error  Expected indentation of 4 space characters but found 8   indent
  12:13  error  Expected indentation of 8 space characters but found 12  indent
  15:13  error  Expected indentation of 8 space characters but found 12  indent
  17:9   error  Expected indentation of 4 space characters but found 8   indent
  18:13  error  Expected indentation of 8 space characters but found 12  indent
  19:13  error  Expected indentation of 8 space characters but found 12  indent
  21:9   error  Expected indentation of 4 space characters but found 8   indent
  22:13  error  Expected indentation of 8 space characters but found 12  indent

```

What's wrong with that? Is the rule `"indent": [2, 4],` is not correct?

**Comment by gaearon** [comment]
Usually, with `switch`, the `case`s shouldn't be indented. (At least, that's a common style I saw.)

should be:

``` js
switch (stuff) {
case STUFF: // <---- not indented
  stuff();
  break;
}
```

**Comment by voronianski** [comment]
@gaearon hmm yeah, strange..

**Comment by gaearon** [comment]
Not really strange—that's a _very_ common style. It's also very popular in Java / C# / C code.

**Comment by gaearon** [comment]
I think the justification for this is that `case` is like a label—not a block.

**Comment by voronianski** [comment]
@gaearon I've just committed an option to allow using indent in `switch`es - https://github.com/voronianski/flux-comparison/commit/0b6a39055df60187ad8014cb681f18ffb5d5c422#diff-1dc6ee56b778cd91e0327b52aaeaa1b9R13

**Comment by voronianski** [comment]
@gaearon so after that linting with CLI is fine:

``` bash
eslint redux/js

/Users/dmitri/github/flux-comparison/redux/js/actions/ActionCreators.js
   5:23  warning  "getState" is defined but never used  no-unused-vars
  31:23  warning  "getState" is defined but never used  no-unused-vars

✖ 2 problems (0 errors, 2 warnings)
```

**Comment by voronianski** [comment]
@gaearon the problem with `eslint` CLI is that if running `eslint redux/` it will also lint files in `build` folder which, of course, contains a lot of errors.

**Comment by gaearon** [comment]
I'm still getting a few more issues. I'll send a PR fixing those.

**Comment by voronianski** [comment]
@gaearon thanks

**Comment by gaearon** [comment]
https://github.com/voronianski/flux-comparison/pull/61
